# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: William Hedley Thompson
email: hedley(at)startmail.com
description: > # this means to ignore newlines until "baseurl:"
  Interests in network neruoscience, temporal networks.<p>
  Also have some interest in some meta-science questions and philosophy.<p> 
  Currently a post doc at Stanford University in the <a href='https://poldracklab.stanford.edu/'>Poldrack Lab</a>.<p> 
  PhD at Karolinska Institutet (<a href='https://ki.se/en/cns/peter-franssons-research-group'>PI Peter Fransson</a>).
  The title of my thesis: <i><a href='https://openarchive.ki.se/xmlui/handle/10616/46007'>Brain networks in time</a></i> which won the department's best thesis for 2017<p>
  Masters at the University of Amsterdam with some time spent at the ESI, Frankfurt (Fries Lab). Bachelors at University of Gothenburg.<p> 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: whedleyt
github_username:  wiheto

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
